<?php 
    $guests = array(
        'JJ-001' => "Bri & Matt",
        'JJ-002' => "Ross & Rachel",
        'JJ-003' => "Jye & Rhianna",
        'JJ-004' => "Jim & Rachael",
        'JJ-005' => "Bellend & Holly",
        'JJ-006' => "Hamish & Sarah",
        'JJ-007' => "Kieth & Marianne",
        'JJ-008' => "Tim & Lily",
        'JJ-009' => "Ben",
        'JJ-010' => "Jim",
        'JJ-011' => "Jax",
        'JJ-012' => "Ryan",
        'JJ-013' => "Tim",
        'JJ-014' => "Emma & Glen",
        'JJ-015' => "Abbey",
        'JJ-016' => "Danillo",
        'JJ-017' => "Jenny & Greig",
        'JJ-018' => "Ros & Pete",
        'JJ-019' => "Juliet & Andrew",
        'JJ-020' => "Kate & Agus",
        'JJ-021' => "Leeanne",
        'JJ-022' => "Brodie & Tas",
        'JJ-023' => "Riley & Ryan",
        'JJ-024' => "Cheryl & Shane",
        'JJ-025' => "Lachlan",
        'JJ-026' => "Jesh & Sasha",
        'JJ-027' => "Terry & Lisa",
        'JJ-028' => "Jess",
        'JJ-029' => "Ash",
        'JJ-030' => "Emily",
        'JJ-031' => "Len, Russi & Pop",
        'JJ-032' => "Bruce & Janelle",
        'JJ-033' => "Ken",
        'JJ-034' => "Nick & Judy",
        'JJ-035' => "Farmer Bob",
        'JJ-036' => "Shane & Kerry",
        'JJ-037' => "Vanessa & Liam",
        'JJ-038' => "Jarrod & Lily",
        'JJ-039' => "Sahil",
        'JJ-040' => "Young",
        'JJ-041' => "Brad & Emily",
        'JJ-042' => "Johnny",
        'JJ-043' => "Tom",
        'JJ-044' => "Nathan",
        'JJ-045' => "Maddie",
        'JJ-046' => "Holly",
        'JJ-047' => "Josie",
        'JJ-048' => "Sam & Maeve",
        'JJ-049' => "Aaron & Brodie",
        'JJ-050' => "Cal & Kath",
        'JJ-051' => "Jemimah & Abe",
        'JJ-052' => "Liv & Ben",
        'JJ-053' => "Gianne",
        'JJ-054' => "Sam",
        'JJ-055' => "Alex & Chelsea",
        'JJ-056' => "Martin",
        'JJ-057' => "James",
        'JJ-058' => "Darcy",
        'JJ-059' => "Pat",
        'JJ-060' => "Dan & Alice",
        'JJ-061' => "Gabe",
        'JJ-062' => "Noah & Priscilla",
        'JJ-063' => "Jackson",
        'JJ-064' => "Jason",
        'JJ-065' => "Albina & Amadeus",
        'JJ-066' => "Luke & Jaslyn",
        'JJ-067' => "Nathan & Seanna",
        'JJ-068' => "Anna",
        'JJ-069' => "Jamie",
        'JJ-070' => "Chris & Sarah",
        'JJ-071' => "Marc",
        'JJ-072' => "Jess"
    );

    session_start();
    $_SESSION['code'] = $_POST['code'];
    $code = $_SESSION['code'];
    $_SESSION['name'] = $guests[$code];

    header("Location: /rsvp/form.php");
    exit();
?>